config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/user' => "art_pieces#index", :as => :user_root
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :art_pieces, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
    resources :bookings, only: %i[new create]
  end

  resources :users, only: %i[show]

  resources :bookings, only: %i[edit update destroy] do
    resources :ratings, only: %i[new create]
  end

  resources :ratings, only: %i[edit update destroy]
end

app/models/art_piece.rb
class ArtPiece < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many_attached :photos

  GENRES = ["abstract", "architecture", "landscape", "seascape", "portrait", "still life", "animals"]

  validates_presence_of :name, :genre, :description
  validates :genre, inclusion: { in: GENRES }

  def live_bookings
    bookings.filter { |booking| booking.end_date >= Date.today }
            .sort { |a, b| a.start_date <=> b.start_date }
  end

  def valid_booking?(d_start, d_end)
    b = bookings.filter do |booking|
      straddles_start_date = booking.end_date > d_start && booking.start_date <= d_start
      straddles_end_date = booking.start_date < d_end && booking.end_date > d_end
      straddles_start_date || straddles_end_date
    end
    b.empty?
  end
end

app/controllers/art_pieces_controller.rb
class ArtPiecesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show update destroy]
  before_action :set_art_piece, only: %i[ show edit update destroy ]

  def index
    @art_pieces = policy_scope(ArtPiece)
    @art_pieces = @art_pieces.filter { |art| art.available_for_rent }
    filter_by(params)
    sort_by(params)
    @sort_options = ["None", "Top Rated", "Price ascending", "Price descending"]
    @sort_options.delete(params[:sort])
  end

  def new
    @art_piece = ArtPiece.new()
    authorize @art_piece
  end

  def show
    # lon, lat = mapbox_coordinates
    # @map_image_url = "https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/pin-s+545454(#{lon},#{lat})/#{lon},#{lat},12.05,0/1000x300?access_token=#{ENV['MAPBOX_API']}"
    @booking = Booking.new()
    @booking.art_piece = @art_piece
    @url = user_signed_in? ? art_piece_bookings_path(@art_piece) : new_user_session_path
    @verb = user_signed_in? ? :post : :get
  end

  def create
    @art_piece = ArtPiece.new(art_piece_params)
    @art_piece.user = current_user
    authorize @art_piece

    if @art_piece.save
      @art_piece.update(art_piece_photos)
      redirect_to art_piece_path(@art_piece), alert: 'Art piece submitted sucessfully'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @art_piece.update(art_piece_edit_params)
      if params[:art_piece][:photos].count > 1
        @art_piece.update(art_piece_photos)
      end
      redirect_to art_piece_path(@art_piece)
    else
      render :edit
    end
  end

  def destroy
    if @art_piece.live_bookings.empty?
      @art_piece.destroy
      redirect_to art_pieces_path, method: :get, notice: 'Art piece was successfully destroyed.'
    else
      redirect_to art_piece_path(@art_piece), notice: "Can't delete art with active bookings."
    end
  end

  private

  def art_piece_params
    params.require(:art_piece).permit(:name, :genre, :description, :cost_per_day, :available_for_rent, photos: [])
  end

  def art_piece_edit_params
    params.require(:art_piece).permit(:name, :genre, :description, :cost_per_day, :available_for_rent)
  end

  def art_piece_photos
    params.require(:art_piece).permit(photos: [])
  end

  def set_art_piece
    @art_piece = ArtPiece.find_by_id(params[:id])
    if @art_piece
      authorize @art_piece
    else
      redirect_to art_pieces_path
    end
  end

  def mapbox_coordinates
    url = "https://api.mapbox.com/geocoding/v5/mapbox.places/#{@art_piece.user.address}.json"
    res = JSON.parse(HTTP.get(url, params: {access_token: ENV['MAPBOX_API']}).body)
    res["features"].first["geometry"]["coordinates"]
  end

  def filter_by(params)

    if params[:genres]
      @art_pieces = @art_pieces.filter do |art_piece|
        params[:genres].include?(art_piece.genre)
      end
    end

    if params[:start_date] || params[:end_date]
      unless (params[:start_date].empty? && params[:end_date].empty?)
        params[:start_date] = params[:end_date] if params[:start_date].empty?
        params[:end_date] = params[:start_date] if params[:end_date].empty?

        if params[:start_date] || params[:end_date]
          @art_pieces = @art_pieces.filter do |art_piece|
            art_piece.valid_booking?(
              params[:start_date] || params[:end_date],
              params[:end_date] || params[:start_date]
            )
          end
        end
      end
    end
  end

  def sort_by(params)

    params[:sort] = params[:commit] unless (params[:commit]||'').include?('Apply')

    # add top rated sort by average if possible
    if params[:sort] === "Price ascending"
      @art_pieces = @art_pieces.sort_by { |a| a.cost_per_day }
    elsif params[:sort] === "Price descending"
      @art_pieces = @art_pieces.sort_by { |a| -a.cost_per_day }
    end

  end
end

app/views/art_pieces/edit.html.erb
  <%= render 'shared/art_form', art_piece: @art_piece %>

app/views/art_pieces/index.html.erb
<div class="art-index-container">
  <%= form_tag art_pieces_path, method: :get, data: {controller: "datefield"} do %>
    <div class="row position-relative">
      <div class="sticky-column col-12 col-sm-4 col-md-2 bg-success">
        <%= render "shared/index_filter_form" %>
      </div>
      <div class="col-12 col-sm-6 offset-sm-6 col-md-10 offset-md-2 border-start border-warning">
        <%= render 'shared/sort_menu' %>
        <div class="container mt-3 art-piece-cards-container">
          <% @art_pieces.each do |art_piece| %>
            <%= render "shared/art_piece_cards", art_piece: art_piece %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/art_pieces/new.html.erb
  <%= render 'shared/art_form', art_piece: @art_piece %>

app/views/art_pieces/show.html.erb
  <div class="container pt-3">
    <%= link_to art_pieces_path, class: "text-secondary mt-3" do %>
      <i class="fas fa-arrow-left"></i> Back to Gallery
    <% end %>
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <% if !@art_piece.photos.empty? %>
          <div class = "art-images m-1 d-flex flex-column align-items-center">
            <%= cl_image_tag(@art_piece.photos.first.key, folder: "artly") %>
        <% else %>
          <div class="text-center m-3">
            No photos
        <% end %>
        </div>
      </div>
      <div class="col-sm-12 col-md-6">
        <div class="art-info m-1">
          <h1 class="border-bottom border-primary text-dark p-1 m-0 text-end">
            <%= @art_piece.name.upcase%>
          </h1>
          <p class="art-genre text-end text-secondary mt-0 mb-3 p-0"><em><%= @art_piece.genre %></em></p>
          <p class="art-description p-1 text-secondary">
            <%= @art_piece.description %>
          </p>
          <p class="mb-0 text-secondary" id="cost" data-cost=<%= @art_piece.cost_per_day %>><strong>Cost per day: £<%= @art_piece.cost_per_day %></strong></p>
          <% if current_user == @art_piece.user %>
          <p class="mt-0 text-secondary">Available for rent: <%=@art_piece.available_for_rent ? "Yes" : "No" %></p>
          <% end %>
          <% if @map_image_url %>
            <div class="art-map pb-1" style = "background-image: url('<%=@map_image_url%>');">
          <% end %>
          </div>
          <% if current_user != @art_piece.user && @art_piece.available_for_rent %>
            <%= render "shared/booking_form", booking: @booking %>
          <% elsif current_user != @art_piece.user %>
            <div class="m-3 bg-warning d-block text-center text-white shadow rounded">This artpiece is not currently available to rent</div>
          <% else %>
            <div class="text-end">
              <%= link_to "Edit", edit_art_piece_path(@art_piece), class: "btn btn-warning mt-3 text-white" %>
              <%= link_to "Delete", art_piece_path(@art_piece), data: { turbo_method: :delete }, class: "btn btn-outline-warning mt-3 #{'disabled' if !@art_piece.live_bookings.empty?}" %>
              <% if !@art_piece.live_bookings.empty? %>
                <%= render "shared/upcoming_bookings", art_piece: @art_piece %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%=  render "shared/reviews_list", bookings: @art_piece.bookings.sort_by{|b| b.rating ? -b.rating.rating : 0} %>
</div>