config/routes.rb
Rails.application.routes.draw do
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    get '/user' => "art_pieces#index", :as => :user_root
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  root to: "pages#home"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :art_pieces, only: [:new, :create, :edit, :update, :destroy, :index, :show] do
    resources :bookings, only: %i[new create]
  end

  resources :users, only: %i[show]

  resources :bookings, only: %i[edit update destroy] do
    resources :ratings, only: %i[new create]
  end

  resources :ratings, only: %i[edit update destroy]
end

app/views/shared/_art_form.html.erb
<div class="text-primary position-absolute start-0 vh-100 vw-100 p-0 m-0" style = "background-size: cover; background-image: url(<%= image_path 'seascape.jpg' %>);">
  <div class="container shadow p-3 bg-white text-primary mt-3">
    <% if !art_piece.id.nil? %>
      <%= link_to art_piece_path(art_piece), class: "text-secondary" do %>
        <i class="fas fa-arrow-left"></i> Back to <em><%= art_piece.name %></em>
      <% end %>
    <% else %>
      <%= link_to art_pieces_path, class: "text-secondary" do %>
        <i class="fas fa-arrow-left"></i> Back to Gallery
      <% end %>
    <% end %>
    <h2 class = "border-bottom border-secondary text-end">ADD ART FOR RENT</h2>
    <%= simple_form_for(art_piece) do |f| %>
      <%= f.input :name, class: "text-primary" %>
      <%= f.input :description, class: "text-primary" %>
      <%= f.input :cost_per_day, label: "Cost per day (in £)"  %>
      <%= f.input :available_for_rent %>
      <%= f.input :photos, class: "text-dark", as: :file, input_html: { multiple: true }%>
      <%= f.input :genre, collection: ["abstract", "architecture", "landscape", "seascape", "portrait", "still life", "animals"], class: "text-dark" %>
      <div class="text-end">
        <%= f.submit class: "btn btn-warning text-white" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_art_piece_cards.html.erb
<%= link_to art_piece_path(art_piece) do%>
  <div class="art-piece-card-container .text-decoration-none" >
    <% if art_piece.user == current_user && !request.path.include?("users")  %>
      <div class="art-piece-owner-badge">owner</div>
    <% elsif art_piece.user == current_user && request.path.include?("users") && !art_piece.available_for_rent%>
      <div class="art-piece-owner-badge">not rentable</div>
    <% end %>
    <% if !art_piece.photos.empty? %>
      <div><%= cl_image_tag art_piece.photos.first.key, class: "card-img" %></div>
    <% else %>
      <div class="bg-dark text-light card-img"><em>No Photo</em></div>
    <% end %>
    <div class="art-piece-card-details">
      <h4> <%= art_piece.name %> </h4>
      <span><strong>£<%= art_piece.cost_per_day %>/day</strong></span>
    </div>
    <p><%= "#{art_piece.description.strip.first(55)}#{art_piece.description.strip.length > 55 ? "..." : ""}" %></p>

    <div class="art-piece-card-genre">
      <%= art_piece.genre %>
    </div>
  </div>
<% end %>

app/views/shared/_booking_form.html.erb
<div class="container shadow p-3 bg-white text-primary mt-3">
  <%= simple_form_for(booking, url: @url, method: @verb, data: {controller: "datefield total-price"}) do |f| %>
    <%= f.input :start_date, as: :date, html5: true, input_html: { min: Date.today + 1,  "data-action" => "input->datefield#update input->total-price#update", "data-datefield-target" => "startDate", "data-total-price-target" => "firstDate"} %>
    <%= f.input :end_date, as: :date, html5: true, input_html: { min: Date.today + 1, "data-action" => "input->total-price#update", "data-datefield-target" => "endDate", "data-total-price-target" => "secondDate"} %>
    <div style="display: none;" data-total-price-target= "total"></div>
    <div class="text-end">
      <%= f.submit class: "btn btn-warning text-white" %>
    </div>
    <%= f.association :art_piece, as: :hidden %>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% if notice %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="pt-5">
  <footer class="footer text-center text-lg-start">
    <div class="text-center p-3 text-dark";">
      © 2022 Copyright:
      <a class="text-warning" target="_blank" href="https://github.com/smayrhof3r">smayrhof3r |</a>
      <a class="text-warning" target="_blank" href="https://github.com/eyss1234">eyss1234 |</a>
      <a class="text-warning" target="_blank" href="https://github.com/MishaHri">MishaHri |</a>
      <a class="text-warning" target="_blank" href="https://github.com/m0hmmed-a">m0hmmed-a</a>
    </div>
  </footer>
</div>

app/views/shared/_index_filter_form.html.erb
<div class = "index-form d-flex flex-column align-items-center">
  <div class = "w-100 m-0 p-2 position-sticky">
    <%= submit_tag "Apply filters", class: "btn btn-warning text-white mt-3 w-100" %>
    <div class="mt-3">
      Start date
      <%= date_field_tag :start_date, params[:start_date], class: "form-control", min: Date.today + 1, data: {action: "input->datefield#update", datefield_target: "startDate"} %>
    </div>
    <div class="mt-3">
      End date
      <%= date_field_tag :end_date, params[:end_date], class: "form-control", min: Date.today + 1, data: { datefield_target: "endDate"}%>
    </div>
    <div class="mt-3">
      Genres
      <%= select_tag :genres, options_for_select(ArtPiece::GENRES), multiple: true, class: "form-select" %>
    </div>
    <div class="mt-3">
      Sort order
      <%= select_tag :sort, options_for_select([params[:sort]]+@sort_options), class: "form-select"  %>
    </div>
  </div>
  <%= link_to art_pieces_path, class: "mt-3 text-sm text-decoration-none text-secondary" do %>
    clear filters
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar nav-original-color navbar-artly navbar-light justify-content-between position-sticky" data-controller="navbar"
    data-action="scroll@window->navbar#updateNavbar">
      <div class="container-fluid">
    <%= link_to art_pieces_path, class: "navbar-brand" do %>
      <%= image_tag "logo-for-navbar.png", data: {navbar_target: "orig"}  %>
      <%# data: {navbar_target: "logo-orig"} %>
      <%= image_tag "logo-for-navbar-inverted.png", class: "d-none", data: {navbar_target: "inverse"} %>
      <%# data: {navbar_target: "logo-inverse"},  %>
    <% end %>

    <% if user_signed_in? %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav nav-style me-auto position-absolute dropdown-format">
          <li class="nav-item nav-style">
            <%= link_to art_pieces_path, class: "nav-link" do %>
              <i class="fas fa-palette"></i><span class="ms-3">Gallery</span>
            <% end %>
          </li>
          <li class="nav-item nav-style">
            <%= link_to new_art_piece_path, class: "nav-link" do %>
              <i class="fas fa-plus"></i><span class="ms-3">Art for Rent</span>
            <% end %>
          </li>
          <li class="nav-item nav-style">
            <%= link_to user_path(current_user), class: "nav-link" do %>
              <i class="far fa-user"></i><span class="ms-3">My Bookings & Art</span>
            <% end %>
          </li>
          <li class="nav-item nav-style">
            <%= link_to destroy_user_session_path, class: "nav-link" do %>
              <i class="fas fa-sign-out"></i><span class="ms-3">Log out</span>
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link me-3" %>
    <% end %>
  </div>
</div>

app/views/shared/_rating_form.html.erb
 <div class="text-primary position-absolute start-0 vh-100 vw-100 p-0 m-0" style = "background-size: cover; background-image: url(<%= image_path 'seascape.jpg' %>);">
  <div class="container shadow p-3 bg-white text-primary mt-3 text-start">
    <%= simple_form_for(rating, url: @url, method: @method) do |f| %>
        <%= f.input :title, label: "title"  %>
        <%= f.input :review, placeholder: "Leave a review here", label: false  %>
        <%= f.input :rating, label: "Choose rating 1 to 5"  %>
        <div class="text-end">
        <%= f.submit class: "btn btn-warning text-white" %>
        </div>
    <% end %>
  </div>
</div>

app/views/shared/_reviews_list.html.erb
<div class="container mt-3">
  <div class="h3 border-bottom border-primary p-1 mt-3 mb-0 text-start">
  REVIEWS
</div>
  <% bookings.each do |booking| %>
    <% if booking.rating %>
      <div class="text-start mb-3 px-3 pt-3 position-relative">
        <div class="d-flex justify-content-between border-bottom border-secondary">
          <h5 class = "m-0 p-0">
            <strong><%= booking.rating.title %></strong>
          </h5>
          <div class="text-end"><%= "⭐"*booking.rating.rating %></div>
        </div>
        <div class = "art-description text-secondary mt-3 mb-0"><%= booking.rating.review %></div>
        <div class="art-description text-secondary mt-0 p-0 text-end"><em><%=booking.user.email %></em></div>
      </div>
    <% end %>
  <% end %>

</div>

app/views/shared/_sort_menu.html.erb
<div class="text-end">
  <button class="sort-toggler btn btn-success btn-round pb-0" type="button" data-bs-toggle="collapse" data-bs-target="#sortSupportedContent" aria-controls="sortSupportedContent" aria-expanded="false" aria-label="Toggle sort">
    <i class="fas fa-caret-down"></i> Sort
  </button>
</div>
<div class="collapse sort-collapse" id="sortSupportedContent">
    <ul class="navbar-nav position-absolute sort-dropdown">
        <li class="nav-item">
          <%= submit_tag "Top Rated", class: "" %>
        </li>
        <li class="nav-item">
          <%= submit_tag "Price ascending", class: "" %>
        </li>
        <li class="nav-item">
          <%= submit_tag "Price descending", class: "" %>
        </li>
    </ul>
</div>

app/views/shared/_upcoming_bookings.html.erb
<div class="h3 border-bottom border-primary p-1 mt-3 mb-0 text-start">
  UPCOMING BOOKINGS
</div>
<div class="art-notice text-secondary text-end mt-0 mb-3 border-top"><em>art cannot be deleted as there are outstanding bookings</em></div>
<% art_piece.live_bookings.each do |booking| %>
  <div class="card text-start mb-3 art-shadow">
    <div class="card-body">
      <h5 class="mb-2 border-bottom border-secondary"><strong>Booked by: </strong><%= booking.user.email %></h5>
      <p class="m-0"><strong>Start Date: </strong><%=booking.start_date.strftime('%d %B %Y')%></p>
      <p class="m-0"><strong>End Date: </strong><%=booking.end_date.strftime('%d %B %Y')%></p>
    </div>
  </div>
<% end %>

app/views/shared/_user_part_bookings.html.erb
<% @user.past_bookings.each do |booking| %>
  <div class="booking-card-container .text-decoration-none" >
    <% if !booking.art_piece.photos.empty? %>
      <div><%= cl_image_tag booking.art_piece.photos.first.key, class: "card-img" %></div>
    <% else %>
      <div class="bg-dark text-light card-img"><em>No Photo</em></div>
    <% end %>
    <div class="booking-card-details">
      <h3> <%= booking.art_piece.name %> </h3>
      <p><strong>Start Date: </strong><%=booking.start_date.strftime('%d %B %Y')%></p>
      <p><strong>End Date: </strong><%=booking.end_date.strftime('%d %B %Y')%></p>
    </div>  
  </div>
<% end %>

app/views/shared/_user_past_bookings.html.erb
<% @user.past_bookings.each do |booking| %>
  <div class="booking-card-container .text-decoration-none" >
    <% if !booking.art_piece.photos.empty? %>
      <div><%= cl_image_tag booking.art_piece.photos.first.key, class: "card-img" %></div>
    <% else %>
      <div class="bg-dark text-light card-img"><em>No Photo</em></div>
    <% end %>
    <div class="booking-card-details">
      <h3> <%= booking.art_piece.name %> </h3>
      <p><strong>Start Date: </strong><%=booking.start_date.strftime('%d %B %Y')%></p>
      <p><strong>End Date: </strong><%=booking.end_date.strftime('%d %B %Y')%></p>
      <div class="booking-card-buttons">
        <% if booking.rating %>
          <%= link_to "Delete Review", rating_path(booking.rating), method: :delete, class: "btn btn-outline-warning mt-3 btn-sm" %>
          <%= link_to "Edit Review", edit_rating_path(booking.rating), class: "btn btn-warning mt-3 text-white btn-sm" %>
        <% else %>
          <%= link_to "Add Review", new_booking_rating_path(booking), class: "btn btn-warning mt-3 text-white btn-sm" %>
        <% end %>
    </div>
    </div>

  </div>
<% end %>

app/views/shared/_user_upcoming_bookings.html.erb
<% @user.existing_bookings.each do |booking| %>
  <div class="booking-card-container .text-decoration-none" >
    <% if !booking.art_piece.photos.empty? %>
      <div><%= cl_image_tag booking.art_piece.photos.first.key, class: "card-img" %></div>
    <% else %>
      <div class="bg-dark text-light card-img"><em>No Photo</em></div>
    <% end %>
    <div class="booking-card-details">
      <h3> <%= booking.art_piece.name %> </h3>
      <p><strong>Start Date: </strong><%=booking.start_date.strftime('%d %B %Y')%></p>
      <p><strong>End Date: </strong><%=booking.end_date.strftime('%d %B %Y')%></p>
      <div class="booking-card-buttons">
        <%= link_to "Edit", edit_booking_path(booking), class: "btn btn-warning mt-3 text-white btn-sm" %>
        <%= link_to "Delete", booking_path(booking), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-sm btn-outline-warning mt-3" %>
      </div>
    </div>

  </div>
<% end %>